{{- if .Values.ingress.enabled}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  rules:
  - host: {{ template "domain" . }}
    http:
      paths:
      - backend:
          serviceName: {{ template "fullname" . }}
          servicePort: 80
        path: /
  tls:
  - hosts:
    - {{ template "domain" . }}
    secretName: {{ template "domain" . }}
{{- end}}
